#!/usr/bin/env python3
"""Regenerates core/src/sim/sin_table.inc (quarter-wave sine table in Q30)."""
import math, os
N = 1024
vals = [round(math.sin(i / N * math.pi / 2) * (1 << 30)) for i in range(N + 1)]
vals[N] = 1 << 30
path = os.path.join(os.path.dirname(__file__), '..', 'src', 'sim', 'sin_table.inc')
with open(path, 'w') as f:
    f.write('// Generated by core/tools/gen_tables.py: sin(i / 1024 * pi / 2) in Q30, 1025 entries\n')
    for i in range(0, len(vals), 8):
        f.write('    ' + ', '.join('%d' % v for v in vals[i:i + 8]) + ',\n')
